config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: "books#index"
    get "/home", to: "books#index"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/search", to: "search#search"
    get "/forgot" , to: "password_resets#new"
    get "/password_reset_path" , to: "password_resets#edit"
    get "/addemployee", to: "users#add_employee"
    post "/addemployee", to: "users#create"
    get "/books", to: "books#index"
    get "/show", to: "static_pages#show"
    post "/cart_items", to: "cart_items#create"
    delete "/cart", to: "carts#destroy"
    get "/cart", to: "carts#index"
    resources :orders
    resources :books, only: [:create]
  end

  post "/cart_items/add_quantity", to: "cart_items#update"
  post "/cart_items/reduce", to: "cart_items#update"
  delete "/cart_items/delete", to: "cart_items#destroy"
  get "/new_order", to: "orders#new"
  post "/new_order", to: "orders#create"
  resources :books, only: [:index, :new, :show]
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :update]
  resources :categories, only: [:index] do
    resources :books, only: [:index, :show, :new, :update]
  end

end

app/models/user.rb
class User < ApplicationRecord
  enum user_type: {customer: 0, employee: 1, admin: 2}
  enum gender: {male: 1, female: 2, trans: 3}
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :employees

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  attr_reader :activation_token, :remember_token, :reset_token
  before_create :create_activation_digest
  before_save :email_downcase
  has_secure_password

  validates :name, presence: true,
    length: {maximum: Settings.name_max_length}
  validates :gender,  presence: true, inclusion: {in: genders.keys}
  validates :birthday, presence: true,
    inclusion: {in: (Date.today - 100.years..Date.today)}
  validates :address, presence: true,
    length: {maximum: Settings.address_max_length}
  validates :phone_number, presence: true,
    length: {in:
      Settings.phone_number_min_length..Settings.phone_number_max_length}
  validates :email, presence: true,
    length: {maximum: Settings.email_max_length},
    format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, presence: true, allow_nil: true,
    length: {minimum: Settings.password_min_length}

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password? token
  end

  def activated
    update_columns activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def remember
    @remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def create_reset_digest
    @reset_token = User.new_token
    update_attributes reset_digest:  User.digest(reset_token)
    update_attributes reset_sent_at: Time.zone.now
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < Settings.reset_password_time.hours.ago
  end
  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end

    def gender_attributes_for_select
      genders.map do |gender, _|
        [I18n.t(
          "activerecord.attributes.#{model_name.i18n_key}.genders.#{gender}"
        ), gender]
      end
    end
  end

  private

  def email_downcase
    email.downcase!
  end

  def create_activation_digest
    @activation_token = User.new_token
    self.activation_digest = User.digest activation_token
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:edit, :show, :update, :destroy]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:destroy, :index, :update, :add_employee]

  def index
    @users = User.paginate page: params[:page], per_page: 10
  end

  def new
    @user = User.new
  end

  def create
    if logged_in? && current_user.admin?
      create_by_admin
    else
      create_by_user
    end
  end

  def show
    redirect_to root_url && return unless @user.activated == true
  end

  def edit; end

  def update
    if @user.update_attributes user_params
      flash[:success] = t ".update_success"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    User.find_by(id: params[:id]).destroy
    flash[:success] = t ".delete_success"
    redirect_to users_url
  end

  private
  def create_by_user
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t "activation_mesage"
      redirect_to root_url
    else
      flash[:danger] = t ".create_failed"
      render :new
    end
  end

  def create_by_admin
    @user = User.new admin_params
    if @user.save
      flash[:success] = t "welcome"
      redirect_to users_path
    else
      flash[:danger] = t ".create_failed"
      render :add_employee
    end
  end

  def admin_user
    return if current_user.admin?
    redirect_to root_url
    flash[:danger] = t ".not_admin"
  end

  def user_params
    params.require(:user).permit :name, :gender, :birthday, :address,
      :phone_number, :email, :password, :password_confirmation
  end

  def admin_params
    params.require(:user).permit :name, :gender, :birthday, :address,
      :phone_number, :email, :password, :password_confirmation,
      :user_type
  end

  def logged_in_user
    return if logged_in?
    flash[:danger] = t "log_msg"
    redirect_to login_url
  end

  def correct_user
    redirect_to root_url if @user
    !@user.admin?
  end

  def find_user
    @user = User.find_by id: params[:id]
    return if @user
    flash[:danger] = t "not_found"
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, size: Settings.avatar_user_size
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :name, t(".name") %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :gender, t(".gender") %>
  <%= f.select :gender, User.gender_attributes_for_select, class: "selected" %>

  <%= f.label :birthday, t(".birthday") %>
  <%= f.date_field :birthday, id: "datepicker" %>

  <%= f.label :address, t(".address") %>
  <%= f.text_field :address, class: "form-control" %>

  <%= f.label :phone_number, t(".phone_number") %>
  <%= f.text_field :phone_number, class: "form-control" %>

  <%= f.label :email, t(".email") %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password, t(".password") %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, t(".confirmation") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/add_employee.html.erb
<% provide :title, t(".addemployee_title") %>
<% provide :button_text, t(".addemployee_submit") %>
<div class="container text-center">
  <h1><%= t ".addemployee_title" %></h1>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for User.new do |f| %>
      <%= render "shared/error_messages", object: f.object %>

      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :gender, t(".gender") %>
      <%= f.select :gender, User.gender_attributes_for_select, class: "selected" %>

      <%= f.label :birthday, t(".birthday") %>
      <%= f.date_field :birthday, id: "datepicker" %>

      <%= f.label :address, t(".address") %>
      <%= f.text_field :address, class: "form-control" %>

      <%= f.label :phone_number, t(".phone_number") %>
      <%= f.text_field :phone_number, class: "form-control" %>

      <%= f.label :email, t(".email") %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :password, t(".password") %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, t(".confirmation") %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.hidden_field :user_type, value: "employee" %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% provide :title, t(".edit_title") %>
<% provide :button_text, t(".edit_submit") %>
<div class="container text-center">
  <h1><%= t ".edit_txt1" %></h1>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank"><%= t ".edit_txt2" %></a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t(".user_list") %>
<div class="container text-center">
  <h1><%= t ".user_list" %></h1>
  <h3><%= link_to t(".add_employee"), addemployee_path %></h3>
</div>
<div class="container text-center">

  <%= will_paginate %>
  <% @users.each do |user| %>
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <h1>
            <ul>
              <%= gravatar_for user %>
              <%= user.name %>
              <%= user.address %>
              <%= user.phone_number %>
              <%= user.user_type %>
              <br>
              <% if current_user.admin? && !user.admin? %>
                <%= link_to t(".delete"), user, method: :delete,
                  data: { confirm: t(".sure") } %>
                <%= link_to t(".detail"), user_path(user) %>
                <% if user.employee? %>
                  <%= link_to "Edit", edit_user_path(user) %>
                <% end %>
              <% end %>
            </ul>
          </h1>
        </section>
      </aside>
    </div>
  <% end %>

  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide :title, t(".sign_up") %>
<% provide :button_text, t(".create") %>
<h1><%= t ".sign_up" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="container text-center">
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= gravatar_for @user %>
          <%= @user.name %>
          <%= @user.address %>
          <%= @user.phone_number %>
          <%= @user.user_type %>
        </h1>
      </section>
    </aside>
  </div>
</div>