config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: "books#index"
    get "/home", to: "books#index"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/search", to: "search#search"
    get "/forgot" , to: "password_resets#new"
    get "/password_reset_path" , to: "password_resets#edit"
    get "/addemployee", to: "users#add_employee"
    post "/addemployee", to: "users#create"
    get "/books", to: "books#index"
    get "/show", to: "static_pages#show"
    post "/cart_items", to: "cart_items#create"
    delete "/cart", to: "carts#destroy"
    get "/cart", to: "carts#index"
    resources :orders
    resources :books, only: [:create]
  end

  post "/cart_items/add_quantity", to: "cart_items#update"
  post "/cart_items/reduce", to: "cart_items#update"
  delete "/cart_items/delete", to: "cart_items#destroy"
  get "/new_order", to: "orders#new"
  post "/new_order", to: "orders#create"
  resources :books, only: [:index, :new, :show]
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :update]
  resources :categories, only: [:index] do
    resources :books, only: [:index, :show, :new, :update]
  end

end

app/models/book.rb
require "elasticsearch/model"
class Book < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :category
  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items

  default_scope ->{order created_at: :desc}

  validates :category_id, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :search_book, only: [:index]
  def index
    @categories = Category.order :category_name
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = "Them sach thanh cong"
      redirect_to root_url
    else
      flash[:danger] = "Khong the tao sach"
      render :new
    end
  end

  def show
    @book = Book.find params[:id]
  end

  private

  def search_book
    @book = if params[:query].present?
              Book.search(params[:query]).paginate page: params[:page],
                per_page: Settings.per_page_search
            elsif params[:check] == "1" && params[:query].present? == false
              Category.find(params[:category_id]).books.paginate page: params[:page],
                per_page: Settings.per_page_search
            else
              Book.all.paginate page: params[:page],
                per_page: Settings.per_page
            end
    return if @book
    flash[:danger] = t("not_found")
    redirect_to root_path
  end

  def book_params
    params.require(:book).permit :category_id, :name, :author, :quantity,
      :price, :description
  end
end

app/views/books/_book.html.erb
<div class="col-md-4 product-men">
  <li>
    <div class="men-pro-item simpleCart_shelfItem">
      <div class="men-thumb-item">
        <%= link_to image_tag("https://goo.gl/kLoSjg", alt: "Image",
        class: "img-responsive")%>
        <div class="men-cart-pro">
          <div class="inner-men-cart-pro">
            <%= link_to "Quick View", book_path(book, :id),
              class: "link-product-add-cart"%>
          </div>
        </div>
        <span class="product-new-top">New</span>
      </div>
      <div class="item-info-product ">
        <h4>
          <p><%= link_to book.name, book_path(book, :id) %></p>
          <p><%= link_to book.author, "#" %></p>
        </h4>
        <div class="info-product-price">
          <span class="item_price"><%= number_to_currency book.price %></span>
          <del>$20.00</del>
        </div>
        <%= button_to t("add_to_cart"), cart_items_path(book_id: book.id),
        class: "btn btn-primary" %>
      </div>
    </div>
  </li>
</div>

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :category_id, "Categoty" %>
  <%= f.text_field :category_id, class: "form-control" %>

  <%= f.label :name, "Name" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :author, "Author" %>
  <%= f.text_field :author, class: "form-control" %>

  <%= f.label :quantity, "Quantity" %>
  <%= f.text_field :quantity, class: "form-control" %>

  <%= f.label :price, "Price" %>
  <%= f.text_field :price, class: "form-control" %>

  <%= f.label :description, "Description" %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/books/index.html.erb
<% provide :title, t("home_title") %>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= link_to image_tag("jumbotronbackground.jpg", style: "width: 100%;", alt: "Banner 1")%>
    </div>

    <div class="item">
      <%= link_to image_tag("banner2.jpg", style: "width: 100%;", alt: "Banner 2")%>
    </div>

    <div class="item">
      <%= link_to image_tag("banner3.jpg", style: "width: 100%;", alt: "Banner 3")%>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<!-- //banner -->

<!-- top Products -->
<div class="ads-grid">
  <div class="container">
    <!-- tittle heading -->
    <h3 class="tittle-w3l">Our Top Products
      <span class="heading-style">
        <i></i>
        <i></i>
        <i></i>
      </span>
    </h3>
    <!-- //tittle heading -->
    <!-- product left -->
    <div class="side-bar col-md-3">
      <div class="search-hotel">
        <h3 class="agileits-sear-head">Search Here..</h3>
      </div>
      <div>
        <%= form_for search_path, method: :get do |f| %>
          <%= text_field_tag :query, params[:query],
            placeholder: "Book name, author..." %>
          <%= button_to "", name: nil, class: "btn btn-default",
            "aria-label" => "Left Align" do %>
            <span class="glyphicon glyphicon-search" aria-hidden="true"> </span>
          <% end %>
        <% end %>
      </div>
      <div class="range">
        <h3 class="agileits-sear-head">Categories</h3>
        <ul class="dropdown-menu6">
          <% @categories.each do |category| %>
            <li>
              <%= link_to "books" do %>
                <%= link_to category.category_name, category_books_path(category_id: category.id, check: 1) %>
                <%= category.books.count %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <!-- price range -->
      <div class="left-side">
        <h3 class="agileits-sear-head">Price range</h3>
        <ul class="dropdown-menu6">
          <li>
            <input type="checkbox" class="checked">
            <span class="span">0$ - 20$</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">20$ - 50$</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">50$ - 100$</span>
          </li>
        </ul>
      </div>
      <!-- //price range -->
      <!-- food preference -->
      <div class="left-side">
        <h3 class="agileits-sear-head">Food Preference</h3>
        <ul>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">Vegetarian</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">Non-Vegetarian</span>
          </li>
        </ul>
      </div>
      <!-- //food preference -->
      <!-- discounts -->
      <div class="left-side">
        <h3 class="agileits-sear-head">Discount</h3>
        <ul>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">5% or More</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">10% or More</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">20% or More</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">30% or More</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">50% or More</span>
          </li>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">60% or More</span>
          </li>
        </ul>
      </div>
      <!-- //discounts -->
      <!-- reviews -->
      <div class="customer-rev left-side">
        <h3 class="agileits-sear-head">Customer Review</h3>
        <ul>
          <li>
            <a href="#">
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star" aria-hidden="true"></i>
              <i class="fa fa-star" aria-hidden="true"></i>
              <span>5.0</span>
            </a>
          </li>
        </ul>
      </div>
      <!-- //reviews -->
      <!-- cuisine -->
      <div class="left-side">
        <h3 class="agileits-sear-head">Cuisine</h3>
        <ul>
          <li>
            <input type="checkbox" class="checked">
            <span class="span">South American</span>
          </li>
        </ul>
      </div>
      <!-- //cuisine -->
      <!-- deals -->
      <div class="deal-leftmk left-side">
        <h3 class="agileits-sear-head">Special Deals</h3>
        <div class="special-sec1">
          <div>
            <%= link_to image_tag("2.jpg", alt: " ", class: "special-image") %>
          </div>
          <div>
            <h3>Lay's Potato Chips</h3>
            <a href="#">$18.00</a>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>
      <!-- //deals -->
    </div>
    <!-- //product left -->
    <!-- product right -->
    <div class="agileinfo-ads-display col-md-9">
      <div class="wrapper">
        <!-- first section (nuts) -->
        <div class="product-sec1">
          <h3 class="heading-tittle">Top Sale</h3>
          <ul>
            <% @book.each do |book| %>
              <%= render "books/book", book: book %>
            <% end %>
          </ul>
          <p><%= will_paginate @book %></p>
          <div class="clearfix"></div>
        </div>
      </div>
    </div>
    <!-- //product right -->
  </div>
</div>
<!-- //top products -->
<!-- special offers -->
<div class="featured-section" id="projects">
  <div class="container">
    <!-- tittle heading -->
    <h3 class="tittle-w3l">Special Offers
      <span class="heading-style">
        <i></i>
        <i></i>
        <i></i>
      </span>
    </h3>
    <!-- //tittle heading -->
    <div class="content-bottom-in">
      <ul id="flexiselDemo1">
        <% 4.times do %>
          <li class="slide-footer">
            <div class="w3l-specilamk">
              <div class="speioffer-agile">
                <%= link_to image_tag("3.jpg", alt: " ", class: "slide_foot") %>
              </div>
              <div class="product-name-w3l">
                <h4>
                  <a href="#">Aashirvaad, 5g</a>
                </h4>
                <div class="w3l-pricehkj">
                  <h6>$220.00</h6>
                  <p>Save $40.00</p>
                </div>
                <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
                  <input type="submit" name="submit" value="Add to cart" class="button" />
                </div>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<% provide :title, "Add Book" %>
<% provide :button_text, "Create" %>
<h1><%= "Add Book" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "books/form" %>
  </div>
</div>

app/views/books/show.html.erb
<% provide :title, t("home_title") %>
<div class="container">
  <div class="row">
    <div class="col">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <%= link_to t(".home"), root_path %>
          </li>
          <li class="breadcrumb-item">
            <%= link_to t(".book"), "#" %>
          </li>
          <li class="breadcrumb-item" aria-current="page">
            <%= @book.name %>
          </li>
        </ol>
      </nav>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-5 item-photo">
      <%= link_to image_tag("https://goo.gl/kLoSjg", alt: "Image", class: "img_thumb")%>
    </div>
    <div class="col-sm-7 book_info">
      <h3><%= @book.name %></h3>
      <h5>
        <%= t ".by" %>
        <a href="#" class="author_info"><%= @book.publisher %></a> ·
      </h5>
      <h5>
        <%= t ".author" %>:
        <a href="#" class="author_info"><%= @book.author %></a> ·
      </h5>
      <h3 class="title-price">
        <small><%= t ".price" %>: </small>
      </h6>
      <h3><%= @book.price %></h3>
      <h3 class="title-price">
        <small><%= t ".discount" %>: <%= @book.discount %>%</small>
      </h6>
      <div class="section">
        <h3 class="title-description">
          <small><%= t ".description" %>: </small>
          <h5><%= @book.description %></h5>
        </h3>
      </div>
      <div class="section btn_add_to_cart">
        <%= button_to t("add_to_cart"), cart_items_path(book_id: @book.id),
          class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>