config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: "books#index"
    get "/home", to: "books#index"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/search", to: "search#search"
    get "/forgot" , to: "password_resets#new"
    get "/password_reset_path" , to: "password_resets#edit"
    get "/addemployee", to: "users#add_employee"
    post "/addemployee", to: "users#create"
    get "/books", to: "books#index"
    get "/show", to: "static_pages#show"
    post "/cart_items", to: "cart_items#create"
    delete "/cart", to: "carts#destroy"
    get "/cart", to: "carts#index"
    resources :orders
    resources :books, only: [:create]
  end

  post "/cart_items/add_quantity", to: "cart_items#update"
  post "/cart_items/reduce", to: "cart_items#update"
  delete "/cart_items/delete", to: "cart_items#destroy"
  get "/new_order", to: "orders#new"
  post "/new_order", to: "orders#create"
  resources :books, only: [:index, :new, :show]
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :update]
  resources :categories, only: [:index] do
    resources :books, only: [:index, :show, :new, :update]
  end

end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :books, through: :cart_items

  def sub_total
    sum = 0
    cart_items.each do |cart_item|
      sum += cart_item.total_price
    end

    sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = @current_cart
    @cart = Cart.find_by user_id: params[:current_user] if logged_in?
  end

  def destroy
    @cart = @current_cart
    @cart.destroy
    session[:cart_id] = nil
    flash[:success] = t("delete_cart")
    redirect_to cart_path
  end
end

app/views/carts/_cart_logged_in.html.erb
<% if @cart.cart_items.count == 0 %>
  <p class="text-center">
    <%= t "please_back" %>
    <%= link_to t("go_back"), root_path %>
    <%= t "and_add" %>
  </p>
<% else %>
  <ul>
    <% if !@cart_item.nil? && @cart_item.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @cart_item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <table class="table">
      <thead>
        <tr>
          <th><%= t "item" %></th>
          <th><%= t "price" %></th>
          <th><%= t "quantity" %></th>
          <th><%= t "remove" %></th>
          <th><%= t "total_price" %></th>
        </tr>
      </thead>
      <tbody>
        <% @cart.cart_items.each do |cart_item| %>
          <tr>
            <td><%= cart_item.book.name %></td>
            <td><%= number_to_currency(cart_item.book.price) %></td>
            <td><%= cart_item.quantity %>
              <span>
                <%= link_to "",
                  cart_items_add_quantity_path(id: cart_item, check: 0),
                  class: "glyphicon glyphicon-plus",
                  method: :post %>
              </span>
              <span>
                <%= link_to "",
                  cart_items_reduce_path(id: cart_item, check: 1),
                  class: "glyphicon glyphicon-minus",
                  method: :post %>
              </span>
            </td>
            <td>
              <%= link_to t("remove"),
                cart_items_delete_path(id:cart_item),
                method: :delete %>
            </td>
            <td>
              <%= number_to_currency(cart_item.total_price) %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th scope="row" colspan="4"><%= t "totals" %></th>
          <td><%= number_to_currency(@cart.sub_total) %></td>
        </tr>
      </tfoot>
    </table>
  </ul>
  <%= button_to t("order"), orders_path(id: @cart.id),
    class: "btn btn-primary" %>
<% end %>

app/views/carts/_cart_not_logged_in.html.erb
<% if @cart.cart_items.count == 0 %>
  <p class="text-center">
    <%= t "please_back" %>
    <%= link_to t("go_back"), root_path %>
    <%= t "and_add" %>
  </p>
<% else %>
  <ul>
    <% if !@cart_item.nil? && @cart_item.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @cart_item.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <table class="table">
      <thead>
        <tr>
          <th><%= t "item" %></th>
          <th><%= t "price" %></th>
          <th><%= t "quantity" %></th>
          <th><%= t "remove" %></th>
          <th><%= t "total_price" %></th>
        </tr>
      </thead>
      <tbody>
        <% @cart.cart_items.each do |cart_item| %>
          <tr>
            <td><%= cart_item.book.name %></td>
            <td><%= number_to_currency(cart_item.book.price) %></td>
            <td><%= cart_item.quantity %>
              <span>
                <%= link_to "",
                  cart_items_add_quantity_path(id: cart_item, check: 0),
                  class: "glyphicon glyphicon-plus",
                  method: :post %>
              </span>
              <span>
                <%= link_to "",
                  cart_items_reduce_path(id: cart_item, check: 1),
                  class: "glyphicon glyphicon-minus",
                  method: :post %>
              </span>
            </td>
            <td>
              <%= link_to t("remove"),
                cart_items_delete_path(id:cart_item),
                method: :delete %>
            </td>
            <td>
              <%= number_to_currency(cart_item.total_price) %>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th scope="row" colspan="4"><%= t "totals" %></th>
          <td><%= number_to_currency(@cart.sub_total) %></td>
        </tr>
      </tfoot>
    </table>
  </ul>
  <%= link_to t("order"), new_order_path,
    class: "btn btn-primary" %>
<% end %>

app/views/carts/index.html.erb
<% provide :title, t("cart") %>
<div class="container text-center">
  <div>
    <div class="col-sm-12">
      <div class="shopping-cart">
        <h2><%= t "cart" %></h2>
        <% if logged_in? %>
          <%= render "carts/cart_logged_in" %>
        <% else %>
          <%= render "carts/cart_not_logged_in" %>
        <% end %>
      </div>
    </div>
  </div>
</div>