config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root to: "books#index"
    get "/home", to: "books#index"
    get "/help", to: "static_pages#help"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/search", to: "search#search"
    get "/forgot" , to: "password_resets#new"
    get "/password_reset_path" , to: "password_resets#edit"
    get "/addemployee", to: "users#add_employee"
    post "/addemployee", to: "users#create"
    get "/books", to: "books#index"
    get "/show", to: "static_pages#show"
    post "/cart_items", to: "cart_items#create"
    delete "/cart", to: "carts#destroy"
    get "/cart", to: "carts#index"
    resources :orders
    resources :books, only: [:create]
  end

  post "/cart_items/add_quantity", to: "cart_items#update"
  post "/cart_items/reduce", to: "cart_items#update"
  delete "/cart_items/delete", to: "cart_items#destroy"
  get "/new_order", to: "orders#new"
  post "/new_order", to: "orders#create"
  resources :books, only: [:index, :new, :show]
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :edit, :update]
  resources :categories, only: [:index] do
    resources :books, only: [:index, :show, :new, :update]
  end

end

app/views/layouts/_admin.html.erb
<li><%= link_to t(".user_list"), users_path %></li>
<li><%= link_to t(".stastitics"), "#" %></li>
<li class="dropdown">
  <%= link_to "#", class: "dropdown-toggle",
    data: {toggle: "dropdown"} do %>
    <%= @current_user.name %>
    <b class="caret"></b>
  <% end %>
  <ul class="dropdown-menu">
    <li><%= link_to t("profile"), current_user %></li>
    <li><%= link_to t("update"), edit_user_path(current_user) %></li>
    <li><%= link_to t("settings"), "#" %></li>
    <li class="divider"></li>
    <li>
      <%= link_to t("signout"), logout_path, method: :delete %>
    </li>
  </ul>
</li>

app/views/layouts/_customer.html.erb
<li class="dropdown">
  <%= link_to "#", class: "dropdown-toggle",
    data: {toggle: "dropdown"} do %>
    <%= @current_user.name %>
    <b class="caret"></b>
  <% end %>
  <ul class="dropdown-menu">
    <li><%= link_to "Lich su mua hang", orders_path %></li>
    <li><%= link_to t("profile"), current_user %></li>
    <li><%= link_to t("update"), edit_user_path(current_user) %></li>
    <li><%= link_to t("settings"), "#" %></li>
    <li class="divider"></li>
    <li>
      <%= link_to t("signout"), logout_path, method: :delete %>
    </li>
  </ul>
</li>

app/views/layouts/_employee.html.erb
<li><%= link_to t(".add_book"), new_book_path %></li>
<li><%= link_to t(".order_list"), orders_path %></li>
<li class="dropdown">
  <%= link_to "#", class: "dropdown-toggle",
    data: {toggle: "dropdown"} do %>
    <%= @current_user.name %>
    <b class="caret"></b>
  <% end %>
  <ul class="dropdown-menu">
    <li><%= link_to t("history_order"), "#" %></li>
    <li><%= link_to t("profile"), current_user %></li>
    <li><%= link_to t("update"), edit_user_path(current_user) %></li>
    <li><%= link_to t("settings"), "#" %></li>
    <li class="divider"></li>
    <li>
      <%= link_to t("signout"), logout_path, method: :delete %>
    </li>
  </ul>
</li>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="clearfix"></div>
    <div class="footer-info w3-agileits-info">
      <div class="col-sm-5 address-right">
        <div class="col-xs-6 footer-grids">
          <h3>Categories</h3>
          <ul>
            <li>
              <a href="#">Grocery</a>
            </li>
          </ul>
        </div>
        <div class="col-xs-6 footer-grids agile-secomk">
          <ul>
            <li>
              <a href="#">Snacks & Beverages</a>
            </li>
          </ul>
        </div>
        <div class="clearfix"></div>
      </div>
      <!-- //footer categories -->
      <!-- quick links -->
      <div class="col-sm-5 address-right">
        <div class="col-xs-6 footer-grids">
          <h3>Quick Links</h3>
          <ul>
            <li>
              <%= link_to t("about_title"), about_path %>
              <li><%= link_to t("contact_title"), contact_path %></li>
              <li><%= link_to t("help_title"), help_path %></li>
              <li><%= link_to t("lang_en"), locale:"en" %></li>
              <li><%= link_to t("lang_vi"), locale:"vi" %></li>
            </li>
          </ul>
        </div>
        <div class="col-xs-6 footer-grids">
          <h3>Get in Touch</h3>
          <ul>
            <li>
              <i class="glyphicon glyphicon-map-marker"></i> 123 Sebastian, USA.</li>
            <li>
              <i class="glyphicon glyphicon-earphone"></i> 333 222 3333 </li>
            <li>
              <i class="glyphicon glyphicon-phone"></i> +222 11 4444 </li>
            <li>
              <i class="glyphicon glyphicon-envelope"></i>
              <a href="#"> mail@example.com</a>
            </li>
          </ul>
        </div>
      </div>
      <!-- //quick links -->
      <!-- social icons -->
      <div class="col-sm-2 footer-grids  w3l-socialmk">
        <h3>Follow Us on</h3>
        <div class="social">
          <ul>
            <li>
              <%= link_to image_tag("facebook.png", all: "", class: "icon-footer") %>
            </li>
            <li>
              <%= link_to image_tag("twiter.png", all: "", class: "icon-footer") %>
            </li>
            <li>
              <%= link_to image_tag("google-plus.png", all: "", class: "icon-footer") %>
            </li>
          </ul>
        </div>
        <div class="agileits_app-devices">
          <h5>Download the App</h5>
          <a href="#">
            <%= link_to image_tag("google-play.png", all: "") %>
          </a>
          <a href="#">
            <%= link_to image_tag("app-store.png", all: "") %>
          </a>
          <div class="clearfix"> </div>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="agile-sometext">
      <div class="sub-some child-momu">
        <h5>Payment Method</h5>
        <ul>
          <li>
            <%= link_to image_tag("pay2.png", all: "") %>
          </li>
          <li>
            <%= link_to image_tag("pay1.png", all: "") %>
          </li>
          <li>
            <%= link_to image_tag("pay3.png", all: "") %>
          </li>
          <li>
            <%= link_to image_tag("pay7.png", all: "") %>
          </li>
          <li>
            <%= link_to image_tag("pay8.png", all: "") %>
          </li>
          <li>
            <%= link_to image_tag("pay9.png", all: "") %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header-bot">
  <div class="header-bot_inner_wthreeinfo_header_mid">
    <!-- header-bot-->
    <div class="col-md-3 logo_agile">
      <h1>
        <%= link_to root_path, class: "home" do %>
          <span>B</span>ook
          <span>S</span>tore
          <%= link_to image_tag("logo2.png", alt: " ") %>
        <% end %>
      </h1>
    </div>
    <!-- header-bot -->
    <div class="col-md-9 header">
      <!-- header lists -->
      <ul>
        <li>
          <a class="aa" href="#">
            <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> Shop Locator</a>
        </li>
        <li>
          <a href="#" data-toggle="modal" data-target="#myModal1">
            <span class="fa fa-truck" aria-hidden="true"></span>Track Order</a>
        </li>
        <li>
          <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span> 001 234 5678
        </li>
        <% if logged_in? %>
          <% if @current_user.admin? %>
            <%= render "layouts/admin" %>
          <% elsif @current_user.employee? %>
            <%= render "layouts/employee" %>
          <% else %>
            <%= render "layouts/customer" %>
          <% end %>
        <% else %>
          <li>
            <%= link_to login_path, class: "btn btn-success" do %>
              <span class="glyphicon glyphicon-log-in"></span>
              <%= t("sign_in") %>
            <% end %>
          </li>
          <li>
            <%= link_to signup_path, class: "btn btn-primary" do %>
              <span class="glyphicon glyphicon-edit"></span>
              <%= t("sign_up") %>
            <% end %>
          </li>
        <% end %>
      </ul>
      <div class="agileits_search">
        <%= form_for search_path, method: :get do |f| %>
          <%= text_field_tag :query, params[:query],
            placeholder: "Book name, author..." %>
          <%= button_to "", name: nil, class: "btn btn-default",
            "aria-label" => "Left Align" do %>
            <span class="glyphicon glyphicon-search" aria-hidden="true"> </span>
          <% end %>
        <% end %>
      </div>
      <div class="top_nav_right">
        <div class="wthreecartaits wthreecartaits2 cart cart box_1">
          <%= link_to cart_path, class: "btn btn-info btn-lg" do %>
            <span class="glyphicon glyphicon-shopping-cart"></span>
            <%= t("cart") %>
          <% end %>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  </div>
</div>
<div class="ban-top">
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="collapse navbar-collapse menu--shylock" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav menu__list">
          <li class="">
            <%= link_to t("home_title"), root_path, class: "nav-stylehead" %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle nav-stylehead" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">English Books
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu multi-column columns-3">
              <div class="agile_inner_drop_nav_info">
                <div class="col-sm-4 multi-gd-img">
                  <ul class="multi-column-dropdown">
                    <li>
                      <a href="#">Category 1</a>
                    </li>
                  </ul>
                </div>
                <div class="col-sm-4 multi-gd-img">
                  <ul class="multi-column-dropdown">
                    <li>
                      <a href="#">Category 2</a>
                    </li>
                  </ul>
                </div>
                <div class="clearfix"></div>
              </div>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle nav-stylehead" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vietnamese Books
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu multi-column columns-3">
              <div class="agile_inner_drop_nav_info">
                <div class="col-sm-6 multi-gd-img">
                  <ul class="multi-column-dropdown">
                    <li>
                      <a href="#">Vietnamese Book 1</a>
                    </li>
                  </ul>
                </div>
                <div class="col-sm-6 multi-gd-img">
                  <ul class="multi-column-dropdown">
                    <li>
                      <a href="#">Vietnamese Book 2</a>
                    </li>
                  </ul>
                </div>
                <div class="clearfix"></div>
              </div>
            </ul>
          </li>
          <li class="">
            <a class="nav-stylehead" href="#">Faqs</a>
          </li>
          <li class="dropdown">
            <a class="nav-stylehead dropdown-toggle" href="#" data-toggle="dropdown">Pages
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu agile_short_dropdown">
              <li>
                <a href="#">Web Icons</a>
              </li>
              <li>
                <a href="#">Typography</a>
              </li>
            </ul>
          </li>
          <li class="">
            <%= link_to t("about_title"), about_path, class: "nav-stylehead" %>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

  </head>
  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>